config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'  

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  namespace :admin do
    root to: 'users#index'
    resources :users
  end

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :tasks, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord

  #關係處理
  belongs_to :user
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings
  #驗證相關
  validates :title, presence: true 
  #任務狀態以及優先度 Enum 設定
  enum state: { 
    created: 0,
    progressing: 1,
    completed: 2
  } 

  enum priority: {
    low: 0,
    normal: 1,
    high: 2
  } 

  #Tag 相關方法擴充
  def self.tagged_with(name)
    Tag.find_by!(name: name).tasks if Tag.find_by(name: name) 
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  #建立關係
  has_many :tasks, :dependent => :destroy
  #驗證欄位相關
  validates :email, presence: true, uniqueness: true
  #使用 Rails 內建密碼安全處理 Bcrypt
  has_secure_password
  #管理員刪除的 callback 處理
  before_destroy :admin_exist_check

  #使用者權限劃分
  enum role: {
    normal: 0,
    admin: 99
  }

  private

  #管理員剩餘一人不可刪除
  def admin_exist_check
    throw :abort if User.where(role: 99).count <= 1
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_check

  private
  
  def admin_check
    render file: "#{Rails.root}/public/404.html", :status => 404 if current_user.admin? == false
  end 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index 
    @users = User.all.page(params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: I18n.t("user.new_success")
    else
      render :new, notice: I18n.t("user.new_fail") 
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: I18n.t("user.update_success")
    else
      render :edit , notice: I18n.t("user.update_fail")
    end
  end

  def destroy
    if User.find(params[:id]).destroy
      redirect_to admin_users_path, notice: I18n.t("user.delete_success")
    else
      redirect_to admin_users_path, notice: I18n.t("user.delete_fail") 
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def authenticate_user!
    redirect_to login_path if current_user.blank?
  end

  def current_user
    return if session[:user_id].blank?
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path, notice: I18n.t("login.error")
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: I18n.t("logout.success")
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task_id, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #從Task Model 撈出所有任務資料存入變數提供給index view用
  def index 
    #搜尋任務標題或狀態時進行處理
    @tasks = current_user.tasks.all
    @tasks = @tasks.where("title LIKE ?", "%#{sort_params[:title]}%") if sort_params[:title].present?
    @tasks = @tasks.tagged_with(sort_params[:title]) if sort_params[:title].present? && @tasks.tagged_with(sort_params[:title]).present?
    @tasks = @tasks.where(state: sort_params[:search_state]) if sort_params[:search_state].present?
    @tasks = sorting_by(@tasks, :priority)
    @tasks = sorting_by(@tasks, :state)
    @tasks = sorting_by(@tasks, :deadline)
    @tasks = sorting_by(@tasks, :created_at)
    @tasks = @tasks.page(params[:page])
  end

  #在新增的頁面提供 @task 給 form 使用
  def new
    @task = Task.new
  end

  #實際創建的處理
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user[:id]

    if @task.save
      redirect_to tasks_path, notice: I18n.t("task.add_success") 
    else
      #新增失敗時借用 new 的頁面，不會讓使用者輸入的資料消失
      render :new , notice: I18n.t("task.add_fail") 
    end
  end

  def show 
  end

  def edit
  end

  def update
    if @task.update(task_params)
      @task.save 
      redirect_to tasks_path, notice: I18n.t("task.update_success") 
    else
      render :edit, notice: I18n.t("task.update_fail") 
    end
  end

  def destroy
    @task.destroy if @task
    redirect_to tasks_path, notice: I18n.t("task.delete_success")
  end

  private
  
  def sorting_by(tasks, column)
    return tasks if sort_params[column].blank?
    case sort_params[column].to_s
    when 'asc' then tasks.order(column => 'asc') # { 'priority' => 'asc' }, { priority: 'asc' }
    when 'desc' then tasks.order(column => 'desc')
    else tasks
    end
  end

  def task_params
    params.require(:task).permit(:title, :description, :priority, :state, :deadline, :tag_list)
  end

  def sort_params
    params.permit(:id, :state, :title, :priority ,:created_at, :deadline, :search, :search_state)
  end

  def find_task_id
    @task = Task.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def sortable(column)
    return search_options.merge(column => 'desc') if params[column].blank?
    sort_options = case params[column].to_s
                   when 'asc' then { column => 'desc' }
                   when 'desc' then { column => 'asc' }
                   else { column => 'desc' }
                   end
    search_options.merge(sort_options)
  end

  def search_options
    params.permit(:title, :search_state, :page, :deadline, :created_at, :priority, :state)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%#處理驗證的錯誤信息%>
<% if user.errors.any? %>
  <ul>
    <% user.errors.full_messages.each do |message| %>
      <li style="color:red; "><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:admin, user] do |f| %>
  <table>
    <tbody>
      <tr><td> <%= t("user.email") %>：<%= f.text_field :email %></td></tr>
      <tr><td><%= t("user.password") %>：<%= f.password_field :password %></td></tr>
      <tr><td><%= t("user.role") %>：<%= f.select :role, options_for_select([[t("role.normal"),"normal"],[t("role.admin"),"admin"]], user.role) %></td></tr>
      <tr><td><%= f.submit %></td></tr>
    </tbody>
  </table>
<% end %>

app/views/admin/users/edit.html.erb
<h1><%= t("user.edit") %></h1>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<h1><%= t("user.list") %></h1>
<p> Hi~ 管理者 <%= current_user.email %> <p>
<p><%= link_to t("user.logout"), logout_path, data: { method: :delete } %></p>

<%= link_to t("user.create"), new_admin_user_path ,class: "btn btn-primary"%>
<br>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <td><%= t("user.email") %></td>
      <td><%= t("user.role")%></td>
      <td><%= t("user.task_count")%></td>
      <td><%= t("user.task_list")%></td>
      <td><%= t("user.edit") %></td>
      <td><%= t("user.delete") %></td>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <%= form_for [:admin, user] do |f| %>
          <td><%= f.select :role, options_for_select([[t("role.normal"),"normal"],[t("role.admin"),"admin"]], user.role), {}, onchange: 'this.form.submit();' %></td>
        <% end %>
        <td><%= user.tasks.count %></td>
        <td><%= link_to t("user.task_list"), admin_user_path(user[:id]), class:"btn btn-primary" %></td>
        <td><%= link_to t("user.edit"), edit_admin_user_path(user[:id]), class:"btn btn-primary" %></td>
        <td><%= link_to t("user.delete"), admin_user_path(user[:id]),method: :delete, class:"btn btn-danger",data: {confirm: t(:delete) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= paginate @users %>

app/views/admin/users/new.html.erb
<h1><%= t("user.new") %></h1>

<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <td><%= t("task.title") %></td>
      <td><%= t("task.description")%></td>
      <td><%= link_to t("task.state"), tasks_path(sortable(:state)) %></td>
      <td><%= link_to t("task.priority"), tasks_path(sortable(:priority)) %></td>
      <td><%= link_to t("task.created_at"), tasks_path(sortable(:created_at)) %></td>
      <td><%= link_to t("task.deadline"), tasks_path(sortable(:deadline)) %></td>
      <td><%= t("task.view")%></td>
      <td><%= t("task.edit")%></td>
      <td><%= t("task.delete")%></td>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= t("states.#{task.state}") %></td>
        <td><%= t("priorities.#{task.priority}")%></td>
        <td><%= task.created_at %></td>
        <td><%= task.deadline %></td>
        <td><%= link_to t(:view), task_path(task[:id]) , class:"btn btn-primary" %></td>
        <td><%= link_to t(:edit), edit_task_path(task[:id]) , class:"btn btn-primary" %></td>
        <td><%= link_to t(:delete), task_path(task[:id]), method: :delete, data:{ confirm:"確認刪除？" } , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= paginate @tasks %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMission</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-warning"> <%= flash[:notice] %> </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%#處理驗證的錯誤信息%>
<% if task.errors.any? %>
  <ul>
    <% task.errors.full_messages.each do |message| %>
      <li style="color:red; "><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%#處理任務表單%>
<table>
  <%= form_for task do |f| %>
    <tr><td><%= t("task.title")%>：<%= f.text_field :title %></td></tr>
    <tr><td><%= t("task.description")%>：<%= f.text_area :description%></td></tr>
    <tr><td><%= t("task.state")%>：<%= f.select :state , options_for_select([[t("states.created"), "created"], [t("states.progressing"), "progressing"], [t("states.completed"), "completed"]]) %></td></tr>
    <tr><td><%= t("task.priority")%>：<%= f.select :priority, options_for_select([[t("priorities.low"),"low"], [t("priorities.normal"),"normal"], [t("priorities.high"),"high"]]) %></td></tr>
    <tr><td><%= t("task.deadline")%>：<%= f.datetime_select :deadline %></td></tr>
    <tr><td><%= t("task.tag_list")%>：<%= f.text_field :tag_list %></td></tr>
    <tr><td><%= f.submit %></td></tr>
  <% end %>
</table>

app/views/tasks/edit.html.erb
<h1><%= t("task.edit")%></h1>

<%= render "form", task: @task %>

<div><%= link_to t("task.back_task_list"), tasks_path ,class: "btn btn-primary"%> </div>

app/views/tasks/index.html.erb
<h1><%= t("task.list") %></h1>
<p>Hi, <%= current_user.email %></p>
<p><%= link_to "Logout", logout_path, data: { method: :delete } %></p>

<%= form_tag(tasks_path, method: :get) do %>
  <%= text_field_tag :title, params[:search], placeholder: t("task.search") %>
  <%= select_tag :search_state , options_for_select([[t("states.any"), nil ] ,[t("states.created"), "0"], [t("states.progressing"), "1"], [t("states.completed"), "2"]]) %>
  <%= submit_tag t("search") %>
<% end %> 
<br>

<%= link_to t("task.create"), new_task_path ,class: "btn btn-primary"%>
<br>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <td><%= t("task.title") %></td>
      <td><%= t("task.description")%></td>
      <td><%= link_to t("task.state"), tasks_path(sortable(:state)) %></td>
      <td><%= link_to t("task.priority"), tasks_path(sortable(:priority)) %></td>
      <td><%= link_to t("task.created_at"), tasks_path(sortable(:created_at)) %></td>
      <td><%= link_to t("task.deadline"), tasks_path(sortable(:deadline)) %></td>
      <td><%= t("task.tag_list")%></td>
      <td><%= t("task.view")%></td>
      <td><%= t("task.edit")%></td>
      <td><%= t("task.delete")%></td>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="title"><%= task.title %></td>
        <td><%= task.description %></td>
        <td class="state"><%= t("states.#{task.state}") %></td>
        <td class="priority"><%= t("priorities.#{task.priority}")%></td>
        <td class="created_at"><%= task.created_at %></td>
        <td class="deadline"><%= task.deadline %></td>
        <td><%= raw task.tags.map(&:name).map{|tag| link_to tag, tasks_path(title: tag)}.join(", ") %></td>
        <td><%= link_to t(:view), task_path(task[:id]) , class:"btn btn-primary" %></td>
        <td><%= link_to t(:edit), edit_task_path(task[:id]) , class:"btn btn-primary" %></td>
        <td><%= link_to t(:delete), task_path(task[:id]), method: :delete, data:{ confirm:"確認刪除？" } , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1><%= t("task.create")%></h1>

<%= render "form", task: @task %>

<div><%= link_to t("task.back_task_list"), tasks_path, class: "btn btn-primary" %> </div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<table>
  <tr><td><%= t("task.description")%>：<%= @task.description %></td></tr>
  <tr><td><%= t("task.state")%>：<%= t("states.#{@task.state}") %></td></tr>
  <tr><td><%= t("task.priority") %>：<%= t("priorities.#{@task.priority}") %></td></tr>
  <tr><td><%= t("task.created_at")%>：<%= @task.created_at %></td></tr>
  <tr><td><%= t("task.deadline")%>：<%= @task.deadline %></td></tr>
</table>

<div><%= link_to t("task.back_task_list"), tasks_path, class: "btn btn-primary" %> </div>